Repository adithyapaib/antiabuseapi, pull requests merged in 2021-10, with the labels that each got.

#17 Added Hindi Gaalis
  api/gali.ts
Labels: Hacktoberfest-accepted

#16 Update gali.ts
  api/gali.ts
Labels: Hacktoberfest-accepted

#12 Update gali.ts
  api/gali.ts
Labels: Hacktoberfest-accepted

#14 Updated gali.ts
  api/gali.ts
Labels: Hacktoberfest-accepted

#30 ✅ Updated gali.ts in Odia language
  api/gali.ts
Labels: hacktoberfest-accepted

#72 Update gali.ts
  api/gali.ts
Labels: good first issue, hacktoberfest-accepted

#78 updated tamil galis
  api/gali.ts
Labels: good first issue, hacktoberfest-accepted

#81 Update gali.ts
  api/gali.ts
Labels: bug, help wanted, good first issue, hacktoberfest-accepted

#88 Update readme.
  README.md
Labels: good first issue, hacktoberfest-accepted

#89 added more hindi gali to gali.ts file
  README.md
  api/gali.ts
Labels: good first issue, hacktoberfest-accepted
